### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by andreasblueher** [tajpouria/TypeGraphQL-Series#2]
Hey Pouria, 

I just wanted to let you know that your boilerplate helped me a lot but I struggled a lot also, because some errors just didn't go away. For example it is crucial to import express for MyContext else response will be of a different type than needed.

**Comment by tajpouria** [comment]
@andreasblueher Thank u for the feedback. I will fix the stuff ASAP.

**Comment by andreasblueher** [comment]
I saw what you added and although thats a good addition to your code, it's not what I meant. Sorry for not being clear enough

[Here](https://github.com/tajpouria/typegraphql-nextjs-boilerplate#loginresolver-and-meresolver) you're defining mycontext, but there is no import there, so Request won't be used from express and rather something else which results in not working code.

Since you have the code somewhere, why don't you upload it to the repo?
