### ISSUE TITLE
Unable to compile TypeScript

### ISSUE THREAD

**Issue by spiv** [tajpouria/TypeGraphQL-Series#3]
[ERROR] 10:49:04 ⨯ Unable to compile TypeScript:
src/modules/user/middleware/IsAuth.ts:5:31 - error TS2339: Property 'userId' does not exist on type 'Session & Partial<SessionData>'.

Any help would be appreciated. Thank you!

**Comment by tajpouria** [comment]
@spiv Thank u for reporting this. [I just fixed a couple of stuff](https://github.com/tajpouria/typegraphql-nextjs-boilerplate/commit/09dc8c8d02b4bcc19e69060722aef523dd0673f6). pull the master branch.
